In [1]:
import pandas as pd

df = pd.read_csv("C:/Users/yuvan/OneDrive/Desktop/ML_projects/Marketing_campaign_analysis/data/marketing_data_cleaned.csv")

In [2]:
high_spend_threshold = df['Total_Spend'].quantile(0.90)

In [3]:
def assign_segment(row):
    if row['Total_Spend'] >= high_spend_threshold:
        return 'High Spender'
    elif row['Income'] > 75000:
        return 'High Income'
    elif row['Response'] == 1:
        return 'Campaign Responder'
    elif row['NumWebVisitsMonth'] > 5:
        return 'High Web Engagement'
    elif row['Children'] > 0:
        return 'Family Customer'
    elif row['Age'] < 30:
        return 'Young Customer'
    else:
        return 'Standard Customer'

In [4]:
df['Customer_Segment'] = df.apply(assign_segment, axis=1)

In [5]:
df['Customer_Segment'].value_counts()

Customer_Segment
High Web Engagement    19696
High Income            15215
Family Customer         8842
High Spender            5546
Campaign Responder      3285
Standard Customer       2821
Young Customer            35
Name: count, dtype: int64

In [6]:
segment_summary = (
    df.groupby('Customer_Segment')
      .agg(
          customers=('ID', 'count'),
          avg_income=('Income', 'mean'),
          avg_spend=('Total_Spend', 'mean'),
          response_rate=('Response', 'mean'),
          avg_web_visits=('NumWebVisitsMonth', 'mean')
      )
      .sort_values('avg_spend', ascending=False)
)

segment_summary

,customers,avg_income,avg_spend,response_rate,avg_web_visits
Customer_Segment,,,,,
High Spender,5546,86265.826542,1953.001082,0.257122,4.085828
High Income,15215,93396.390785,773.561222,0.221492,4.505619
Standard Customer,2821,49929.758135,595.796881,0.000000,2.945409
Campaign Responder,3285,46589.018935,553.207610,1.000000,5.229224
Young Customer,35,48759.128571,427.028571,0.000000,3.057143
Family Customer,8842,37664.728331,363.015381,0.000000,3.240896
High Web Engagement,19696,31079.820715,289.480453,0.000000,7.228219

In [7]:
segment_summary = (
    df.groupby('Customer_Segment')
      .agg(
          customers=('ID', 'count'),
          avg_income=('Income', 'mean'),
          avg_spend=('Total_Spend', 'mean'),
          response_rate=('Response', 'mean'),
          avg_web_visits=('NumWebVisitsMonth', 'mean')
      )
      .sort_values('avg_spend', ascending=False)
)

segment_summary

,customers,avg_income,avg_spend,response_rate,avg_web_visits
Customer_Segment,,,,,
High Spender,5546,86265.826542,1953.001082,0.257122,4.085828
High Income,15215,93396.390785,773.561222,0.221492,4.505619
Standard Customer,2821,49929.758135,595.796881,0.000000,2.945409
Campaign Responder,3285,46589.018935,553.207610,1.000000,5.229224
Young Customer,35,48759.128571,427.028571,0.000000,3.057143
Family Customer,8842,37664.728331,363.015381,0.000000,3.240896
High Web Engagement,19696,31079.820715,289.480453,0.000000,7.228219

In [9]:
df.to_csv("C:/Users/yuvan/OneDrive/Desktop/ML_projects/Marketing_campaign_analysis/data/marketing_data_segmented.csv", index=False)